"""
Módulo de tradução de nomes de colunas.
Fonte canônica única — usada pelo backend (FastAPI) e exposta via
`GET /api/traducoes/colunas` para o frontend consumir.

NÃO duplique este dicionário em outros arquivos.
"""

from __future__ import annotations

import unicodedata

TRADUCOES_COLUNAS = {
    # ── Campos de data/hora ───────────────────────────────────────────────────
    'created_at': 'Data de Criação',
    'updated_at': 'Data de Atualização',
    'deleted_at': 'Data de Exclusão',
    'inserted_at': 'Data de Inserção',
    'timestamp': 'Data/Hora',
    'date_inserted': 'Data de Inserção',
    'date': 'Data',
    'datemoved': 'Data de Movimentação',
    'dateupdated': 'Data de Atualização',
    'processing_date': 'Data de Processamento',
    'effectivedate': 'Data Efetiva',
    'instructionsdate': 'Data das Instruções',
    'instructionsinsertdate': 'Data de Inserção das Instruções',
    'instructionstimestamp': 'Timestamp das Instruções',
    'instructionsinsertdate_userid': 'Usuário da Inserção das Instruções',
    'naf_userid_date': 'Data do Usuário NAF',
    'created_at_userid': 'Usuário da Criação',
    'createdat_userid': 'Usuário da Criação',
    'updated_at_userid': 'Usuário da Atualização',
    'protocoldate': 'Data do Protocolo',
    'startdate': 'Data de Início',
    'hiring_date': 'Data de Contratação',
    'system_date_insert_proposal': 'Data de Inserção da Proposta',
    'start_date': 'Data de Início',
    'end_date': 'Data de Término',
    'enddate': 'Data de Término',
    'canceled_at': 'Data de Cancelamento',
    'closed_at': 'Data de Encerramento',
    'confirmed_at': 'Data de Confirmação',
    'finished_at': 'Data de Conclusão',
    'sent_at': 'Data de Envio',
    'birthdate': 'Data de Nascimento',
    'datecreated': 'Data de Criação',
    'datedeleted': 'Data de Exclusão',
    'dateinserted': 'Data de Inserção',
    'datepaid': 'Data de Pagamento',
    'datesent': 'Data de Envio',
    'daterequested': 'Data de Solicitação',
    'dateclassified': 'Data de Classificação',
    'dateclosed': 'Data de Encerramento',
    'dateviewed': 'Data de Visualização',
    'activitydate': 'Data da Atividade',
    'activity_date': 'Data da Atividade',
    'invoicedate': 'Data da Fatura',
    'paydate': 'Data de Pagamento',
    'payment_date': 'Data de Pagamento',
    'close_date': 'Data de Encerramento',
    'distribution_date': 'Data de Distribuição',
    'prescription_date': 'Data de Prescrição',
    'settlement_date': 'Data de Liquidação',
    'deferment_date': 'Data de Diferimento',
    'impug_date': 'Data de Impugnação',
    'impug_result_date': 'Data do Resultado da Impugnação',
    'citation_date': 'Data de Citação',
    'check_date': 'Data de Conferência',
    'client_legal_receive_date': 'Data de Recebimento Legal do Cliente',
    'client_notification_date': 'Data de Notificação do Cliente',
    'office_receive_date': 'Data de Recebimento no Escritório',
    'sentence_read_date': 'Data de Leitura da Sentença',
    'notification_date': 'Data de Notificação',
    'defendant_calcs_date': 'Data dos Cálculos do Réu',
    'homologated_calcs_date': 'Data dos Cálculos Homologados',
    'perito_calcs_date': 'Data dos Cálculos do Perito',
    'plaintiff_calcs_date': 'Data dos Cálculos do Autor',
    'last_update': 'Última Atualização',
    'lastupdate': 'Última Atualização',
    'index_date': 'Data do Índice',
    'fulfilment_date': 'Data de Cumprimento',
    'causeamount_index_date': 'Data do Índice do Valor da Causa',
    'datestamp': 'Carimbo de Data/Hora',
    'result_datestamp': 'Carimbo de Data/Hora do Resultado',
    'datetime_in': 'Data/Hora de Entrada',
    'datetime_out': 'Data/Hora de Saída',
    'login_time': 'Horário de Login',
    'logout_time': 'Horário de Logout',
    'actualdate': 'Data Real',
    'date_created': 'Data de Criação',
    'date_finished': 'Data de Conclusão',
    'date_start': 'Data de Início',
    'subsidy_date': 'Data do Subsídio',
    'subsidy_receive_date': 'Data de Recebimento do Subsídio',
    'system_date_insert': 'Data de Inserção no Sistema',
    'system_date_observation': 'Data de Observação no Sistema',
    'totalprovamount_date': 'Data do Valor Provisional Total',
    'payment_deadline': 'Vencimento de Pagamento',
    'fataldeadline': 'Prazo Fatal',
    'companydeadline': 'Prazo da Empresa',
    'deliverdeadline01': 'Prazo de Entrega 01',
    'deliverdeadline02': 'Prazo de Entrega 02',
    'deliverdeadline03': 'Prazo de Entrega 03',
    'deliverdeadlineinvoice': 'Prazo de Entrega (Fatura)',
    'paymentdeadline01': 'Vencimento de Pagamento 01',
    'paymentdeadline02': 'Vencimento de Pagamento 02',
    'paymentdeadline03': 'Vencimento de Pagamento 03',
    'paymentdeadlineinvoice': 'Vencimento de Pagamento (Fatura)',
    'protocoldeadline': 'Prazo do Protocolo',
    'duedate': 'Data de Vencimento',
    'closed_at_userid': 'Usuário do Encerramento',
    'finished_at_userid': 'Usuário da Conclusão',
    'sent_at_userid': 'Usuário do Envio',
    'canceled_at_userid': 'Usuário do Cancelamento',
    'confirmed_closed_at': 'Data de Encerramento Confirmado',
    'confirmed_closed_at_userid': 'Usuário do Encerramento Confirmado',
    'confirmed_doc_at': 'Data de Confirmação do Documento',
    'confirmed_doc_userid': 'Usuário da Confirmação do Documento',
    'date_created_userid': 'Usuário da Criação',
    'date_updated_userid': 'Usuário da Última Atualização',
    'dateclosed_timestamp': 'Timestamp de Encerramento',
    'exec_prov_updated_at_userid': 'Usuário da Atualização da Execução Provisória',
    'phase_updated_at_userid': 'Usuário da Atualização de Fase',
    'relevant_updated_at_userid': 'Usuário da Atualização de Relevância',
    'resp_updated_at_userid': 'Usuário da Atualização do Responsável',
    'result_datestamp_userid': 'Usuário do Carimbo de Data do Resultado',
    'cnj_required_updated_at': 'Data de Atualização do CNJ Obrigatório',
    'cnj_required_updated_at_userid': 'Usuário da Atualização do CNJ Obrigatório',
    'charged_amount_userid': 'Usuário do Valor Cobrado',
    'charged_time_userid': 'Usuário do Tempo Cobrado',
    'finish_observations_userid': 'Usuário das Observações de Conclusão',
    'charged_time': 'Tempo Cobrado',
    'activity_time': 'Duração da Atividade',
    'activityhours': 'Horas da Atividade',
    'availablehours': 'Horas Disponíveis',
    'estimatetime': 'Tempo Estimado',
    'hours': 'Horas',
    'time': 'Hora',
    'timelimit': 'Limite de Tempo',

    # ── IDs e chaves ──────────────────────────────────────────────────────────
    'id': 'ID',
    'user_id': 'ID do Usuário',
    'userid': 'ID do Usuário',
    'lawsuit_id': 'ID do Processo',
    'hearing_id': 'ID da Audiência',
    'hearingcontrol_id': 'ID Controle Audiência',
    'person_id': 'ID da Pessoa',
    'client_id': 'ID do Cliente',
    'employee_id': 'ID do Funcionário',
    'from_automatic_prazoid': 'ID do Prazo Automático',
    'fromhearingcontrolid': 'ID do Controle de Audiência',
    'prazoid': 'ID do Prazo',
    'expedientfileid': 'ID do Arquivo de Expediente',
    'av_clientid': 'ID Cliente Avaliação',
    'analise_prov_hearingid': 'ID Audiência Análise Provisória',
    'account_id': 'ID da Conta',
    'accountspayable_id': 'ID das Contas a Pagar',
    'accountsrec_id': 'ID das Contas a Receber',
    'accountsreceivable_id': 'ID das Contas a Receber',
    'activity_id': 'ID da Atividade',
    'adddoc2lawsuitdoc_id': 'ID do Documento Adicionado ao Processo',
    'arearesp_id': 'ID da Área Responsável',
    'auditsubject_id': 'ID do Assunto de Auditoria',
    'auto_debit_account_id': 'ID da Conta de Débito Automático',
    'automaticprazos_jurify_id': 'ID do Prazo Automático Jurify',
    'bankaccount_id': 'ID da Conta Bancária',
    'bank_id': 'ID do Banco',
    'busunit_id': 'ID da Unidade de Negócio',
    'busunitgroup_id': 'ID do Grupo de Unidade de Negócio',
    'busunitid': 'ID da Unidade de Negócio',
    'category_id': 'ID da Categoria',
    'chatmessage_id': 'ID da Mensagem de Chat',
    'claim_id': 'ID do Pedido',
    'claimfundamento_id': 'ID do Fundamento do Pedido',
    'claimid': 'ID do Pedido',
    'client_system_id': 'ID do Sistema do Cliente',
    'clientrequester_id': 'ID do Solicitante do Cliente',
    'close_reason_id': 'ID do Motivo de Encerramento',
    'coligada_id': 'ID da Coligada',
    'comarcaid': 'ID da Comarca',
    'companytype_id': 'ID do Tipo de Empresa',
    'consultsubject_id': 'ID do Assunto de Consulta',
    'contract_id': 'ID do Contrato',
    'controlpanel2accounts_id': 'ID da Conta do Painel de Controle',
    'coordinator_id': 'ID do Coordenador',
    'correspondent_request_id': 'ID da Solicitação do Correspondente',
    'created_user_id': 'ID do Usuário Criador',
    'demandant_area_id': 'ID da Área Demandante',
    'deniedprotocol_id': 'ID do Protocolo Negado',
    'department_id': 'ID do Departamento',
    'desembargador_id': 'ID do Desembargador',
    'docsmetadata_id': 'ID dos Metadados de Documentos',
    'emp_id': 'ID do Funcionário',
    'emp2jobrole_id': 'ID do Cargo do Funcionário',
    'estorno_id': 'ID do Estorno',
    'eventid': 'ID do Evento',
    'expensereport_id': 'ID do Relatório de Despesas',
    'expensereportitem_id': 'ID do Item do Relatório de Despesas',
    'expenserequest_id': 'ID da Solicitação de Despesa',
    'expenserequestitem_id': 'ID do Item da Solicitação de Despesa',
    'expreport_item_id': 'ID do Item do Relatório de Despesas',
    'fail_reason_id': 'ID do Motivo de Falha',
    'formfield_id': 'ID do Campo de Formulário',
    'from_project_id': 'ID do Projeto de Origem',
    'frompublication_id': 'ID da Publicação de Origem',
    'fundamento_id': 'ID do Fundamento',
    'generaldocsmetadata_id': 'ID dos Metadados de Documentos Gerais',
    'generaltask_id': 'ID da Tarefa Geral',
    'generaltaskcontrol_id': 'ID do Controle de Tarefa Geral',
    'group_id': 'ID do Grupo',
    'group_supervisor_id': 'ID do Supervisor do Grupo',
    'hearingparent_id': 'ID da Audiência Principal',
    'hearingtype_id': 'ID do Tipo de Audiência',
    'input_user_id': 'ID do Usuário Inseridor',
    'inventory_id': 'ID do Inventário',
    'item_id': 'ID do Item',
    'jobrole_id': 'ID do Cargo',
    'jobroleid': 'ID do Cargo',
    'judicial_area_id': 'ID da Área Judicial',
    'jurify_pub_id': 'ID da Publicação Jurify',
    'jurispmetadata_id': 'ID dos Metadados de Jurisprudência',
    'jurispsubject_id': 'ID do Assunto de Jurisprudência',
    'lawsuit_coordinator_id': 'ID do Coordenador do Processo',
    'lawsuit_motive_id': 'ID do Motivo do Processo',
    'lawsuit_resp_id': 'ID do Responsável do Processo',
    'lawsuitbudget_id': 'ID do Orçamento do Processo',
    'lawsuitdoc_id': 'ID do Documento do Processo',
    'lawsuitdocmdata_id': 'ID dos Metadados do Documento do Processo',
    'lawsuitdocmetadata_id': 'ID dos Metadados do Documento do Processo',
    'lawsuitdoctype_id': 'ID do Tipo de Documento do Processo',
    'lawsuitid': 'ID do Processo',
    'lawsuitnature_id': 'ID da Natureza do Processo',
    'lawsuitparent_id': 'ID do Processo Principal',
    'lawsuittask_id': 'ID da Tarefa do Processo',
    'limit_id': 'ID do Limite',
    'login_id': 'ID de Login',
    'materia_id': 'ID da Matéria',
    'member_id': 'ID do Membro',
    'msg_id': 'ID da Mensagem',
    'natureid': 'ID da Natureza',
    'opna_id': 'ID da Natureza de Operação',
    'opnature_id': 'ID da Natureza de Operação',
    'opnaturegroup_id': 'ID do Grupo de Natureza de Operação',
    'operationnature_id': 'ID da Natureza de Operação',
    'otherdoc_id': 'ID do Outro Documento',
    'otherdocmetadata_id': 'ID dos Metadados do Outro Documento',
    'otherdocsmetadata_id': 'ID dos Metadados de Outros Documentos',
    'otherlawyer_id': 'ID do Outro Advogado',
    'otherlawyerid': 'ID do Outro Advogado',
    'payable_id': 'ID do Pagável',
    'paymenttype_id': 'ID do Tipo de Pagamento',
    'pedido_id': 'ID do Pedido',
    'pedido2lawsuit_id': 'ID do Pedido do Processo',
    'pericia_control_id': 'ID do Controle de Perícia',
    'permission_id': 'ID da Permissão',
    'permissions_id': 'ID das Permissões',
    'prazo2pub_id': 'ID do Prazo/Publicação',
    'prazo2publication_id': 'ID de Publicação do Prazo',
    'prazo_id': 'ID do Prazo',
    'prazo_owner_id': 'ID do Proprietário do Prazo',
    'print_report_id': 'ID do Relatório Impresso',
    'project_id': 'ID do Projeto',
    'projectid': 'ID do Projeto',
    'protocolmetadata_id': 'ID dos Metadados do Protocolo',
    'protocolrequesttimelimit_id': 'ID do Prazo de Solicitação de Protocolo',
    'pub_class_id': 'ID da Classe de Publicação',
    'pub_classification_id': 'ID da Classificação de Publicação',
    'pub_text_search_term_id': 'ID do Termo de Busca de Texto da Publicação',
    'publicationid': 'ID da Publicação',
    'publicationxml_id': 'ID do XML da Publicação',
    'purchaseorder_id': 'ID do Pedido de Compra',
    'purchaseorderitem_id': 'ID do Item do Pedido de Compra',
    'purchaseorderlimit_id': 'ID do Limite do Pedido de Compra',
    'request_id': 'ID da Solicitação',
    'requester_id': 'ID do Solicitante',
    'sent_to_user_id': 'ID do Usuário Destinatário',
    'starttask_id': 'ID da Tarefa Inicial',
    'sub_judicial_area_id': 'ID da Sub-área Judicial',
    'subclient_id': 'ID do Sub-cliente',
    'supervisor_id': 'ID do Supervisor',
    'supplier_id': 'ID do Fornecedor',
    'task_id': 'ID da Tarefa',
    'taskcontrol_id': 'ID do Controle de Tarefa',
    'tax_id': 'ID do Imposto',
    'taxaccountid': 'ID da Conta Fiscal',
    'taxwithholding_id': 'ID da Retenção de Imposto',
    'tech_assistant_id': 'ID do Assistente Técnico',
    'templatefunction_id': 'ID da Função do Template',
    'templatemetadata_id': 'ID dos Metadados do Template',
    'templateotherlawyer_id': 'ID do Outro Advogado do Template',
    'templatesubject_id': 'ID do Assunto do Template',
    'templatetype_id': 'ID do Tipo de Template',
    'terceiroclient_id': 'ID do Terceiro Cliente',
    'third_party_id': 'ID do Terceiro',
    'thirdparty_id': 'ID do Terceiro',
    'thirdpartyaccess_id': 'ID do Acesso de Terceiros',
    'timesheet_tasks_id': 'ID das Tarefas do Timesheet',
    'transaction_id': 'ID da Transação',
    'transactiondivision_id': 'ID da Divisão de Transação',
    'transactiongroup_id': 'ID do Grupo de Transação',
    'transactionparent_id': 'ID da Transação Principal',
    'update_user_id': 'ID do Usuário Atualizador',
    'user_created_id': 'ID do Usuário Criador',
    'userinserted_id': 'ID do Usuário Inseridor',
    'vara_actual_id': 'ID da Vara Atual',
    'vara_cartorio_id': 'ID do Cartório da Vara',
    'vara_id': 'ID da Vara',
    'varaid': 'ID da Vara',
    'varas_id': 'ID das Varas',
    'payablesid_group': 'Grupo de ID a Pagar',
    'receivablesid_group': 'Grupo de ID a Receber',
    'parentprazoid': 'ID do Prazo Principal',
    'parentmetadata_id': 'ID dos Metadados Principais',
    'automaticprazo_lawsuits_id': 'ID de Processos do Prazo Automático',
    'first_replication_id': 'ID da Primeira Replicação',
    'source_prazoid': 'ID do Prazo de Origem',
    'settle_transactionid': 'ID da Transação de Liquidação',
    'transition_lawsuitid': 'ID do Processo em Transição',
    'hearing_created': 'Audiência Criada',
    'hearingcontrolid': 'ID do Controle de Audiência',
    'hearinglawyerid': 'ID do Advogado da Audiência',
    'personid': 'ID da Pessoa',
    'personid_2': 'ID da Pessoa 2',
    'personid_3': 'ID da Pessoa 3',
    'personid_4': 'ID da Pessoa 4',
    'from_id': 'ID de Origem',
    'to_id': 'ID de Destino',
    'court_division_idcourt_division': 'ID da Divisão do Tribunal',
    'court_idcourt': 'ID do Tribunal',

    # ── Status e tipos ────────────────────────────────────────────────────────
    'status': 'Status',
    'type': 'Tipo',
    'nature': 'Natureza',
    'phase': 'Fase',
    'result': 'Resultado',
    'aut_event': 'Evento Automático',
    'hearing': 'Audiência',
    'from_lawsuit': 'Originário de Processo',
    'event': 'Evento',
    'hearing_type': 'Tipo de Audiência',
    'lawsuit_phase': 'Fase do Processo',
    'lawsuittype': 'Tipo de Processo',
    'activity_type': 'Tipo de Atividade',
    'objecttype': 'Tipo de Objeto',
    'empstatus': 'Status do Funcionário',
    'operation': 'Operação',
    'action': 'Ação',
    'flow': 'Fluxo',
    'sector': 'Setor',
    'region': 'Região',
    'system': 'Sistema',
    'contract_type': 'Tipo de Contrato',
    'doc_type': 'Tipo de Documento',
    'doctype': 'Tipo de Documento',
    'docfiletype': 'Tipo de Arquivo do Documento',
    'entrytype': 'Tipo de Lançamento',
    'finalpayment_type': 'Tipo do Pagamento Final',
    'finishtype': 'Tipo de Conclusão',
    'link_type': 'Tipo de Vínculo',
    'otherdoctype': 'Tipo de Outro Documento',
    'payabletype': 'Tipo de Pagável',
    'paydoctype': 'Tipo de Documento de Pagamento',
    'payment_type': 'Tipo de Pagamento',
    'paymenttype': 'Tipo de Pagamento',
    'person_group': 'Grupo de Pessoa',
    'persontype': 'Tipo de Pessoa',
    'personstatus': 'Status da Pessoa',
    'docstatus': 'Status do Documento',
    'hearingstatus': 'Status da Audiência',
    'processtype': 'Tipo de Processo',
    'protocolstatus': 'Status do Protocolo',
    'pzphase': 'Fase do Prazo',
    'prazophase': 'Fase do Prazo',
    'lawsuitphase': 'Fase do Processo',
    'pjestatus': 'Status no PJe',
    'pubtype': 'Tipo de Publicação',
    'pub_classification': 'Classificação de Publicação',
    'close_reason': 'Motivo de Encerramento',
    'cancel_reason': 'Motivo de Cancelamento',
    'reject_reason': 'Motivo de Rejeição',
    'refuse_reason': 'Motivo de Recusa',
    'resend_reason': 'Motivo de Reenvio',
    'return_message': 'Mensagem de Retorno',
    'risk': 'Risco',
    'classification': 'Classificação',
    'category': 'Categoria',
    'type_old': 'Tipo Antigo',
    'type_bank': 'Tipo do Banco',
    'type_client': 'Tipo do Cliente',
    'type_clientlaw': 'Tipo do Advogado do Cliente',
    'type_corresp': 'Tipo do Correspondente',
    'type_employee': 'Tipo do Funcionário',
    'type_otherlaw': 'Tipo do Outro Advogado',
    'type_supplier': 'Tipo do Fornecedor',
    'type_tech_assistant': 'Tipo do Assistente Técnico',
    'type_witness': 'Tipo da Testemunha',

    # ── Nomes descritivos ─────────────────────────────────────────────────────
    'name': 'Nome',
    'description': 'Descrição',
    'code': 'Código',
    'number': 'Número',
    'value': 'Valor',
    'amount': 'Valor',
    'total': 'Total',
    'filename': 'Nome do Arquivo',
    'lawsuitnumber': 'Número do Processo',
    'location': 'Localização',
    'information': 'Informação',
    'search': 'Busca',
    'term': 'Termo',
    'search_term': 'Termo de Busca',
    'search_term_id': 'ID do Termo de Busca',
    'sigla': 'Sigla',
    'rate': 'Taxa',
    'paymentlimit': 'Limite de Pagamento',
    'account_num': 'Número da Conta',
    'address': 'Endereço',
    'alias': 'Apelido',
    'andamento_text': 'Texto do Andamento',
    'annotations': 'Anotações',
    'approvallevel': 'Nível de Aprovação',
    'area': 'Área',
    'attachment': 'Anexo',
    'attachments': 'Anexos',
    'attachmentother': 'Outro Anexo',
    'autodocnum': 'Número de Documento Automático',
    'body': 'Corpo',
    'branch': 'Filial',
    'business_area': 'Área de Negócio',
    'cep': 'CEP',
    'claim': 'Pedido',
    'claim_en': 'Pedido (Inglês)',
    'claim_text': 'Texto do Pedido',
    'clientcode': 'Código do Cliente',
    'clientcond': 'Condição do Cliente',
    'cnpj': 'CNPJ',
    'cpf': 'CPF',
    'cpfdefendant': 'CPF do Réu',
    'cpfplaintiff': 'CPF do Autor',
    'complement': 'Complemento',
    'complemento': 'Complemento',
    'compliment': 'Elogio',
    'considerations': 'Considerações',
    'contact': 'Contato',
    'days': 'Dias',
    'department': 'Departamento',
    'district': 'Distrito',
    'doc_description': 'Descrição do Documento',
    'doc_name': 'Nome do Documento',
    'doccomplement': 'Complemento do Documento',
    'docnumber': 'Número do Documento',
    'education': 'Escolaridade',
    'email01': 'E-mail 01',
    'email02': 'E-mail 02',
    'estado': 'Estado',
    'filial': 'Filial',
    'function': 'Função',
    'hash': 'Hash',
    'ie': 'Inscrição Estadual',
    'im': 'Inscrição Municipal',
    'imap_email_access': 'Acesso de E-mail IMAP',
    'imapemail': 'E-mail IMAP',
    'impact': 'Impacto',
    'inscricao': 'Inscrição',
    'instance': 'Instância',
    'instance01': 'Instância 01',
    'instance02': 'Instância 02',
    'instancia': 'Instância',
    'instanceextra': 'Instância Extra',
    'instancesup': 'Instância Superior',
    'ip_address': 'Endereço IP',
    'language': 'Idioma',
    'login': 'Login',
    'logo_filename': 'Nome do Arquivo de Logotipo',
    'matter': 'Assunto',
    'minimum': 'Mínimo',
    'motive': 'Motivo',
    'motive2': 'Motivo 2',
    'motive_en': 'Motivo (Inglês)',
    'name_en': 'Nome em Inglês',
    'notification': 'Notificação',
    'num_acc': 'Número da Conta',
    'num_ag': 'Número da Agência',
    'num_bank': 'Número do Banco',
    'oab_uf': 'UF da OAB',
    'object': 'Objeto',
    'observation': 'Observação',
    'pages': 'Páginas',
    'pais': 'País',
    'password': 'Senha',
    'password_date_changed': 'Data de Alteração da Senha',
    'pasta': 'Pasta',
    'pendingnumber': 'Número de Pendências',
    'phone01': 'Telefone 01',
    'phone02': 'Telefone 02',
    'print_option': 'Opção de Impressão',
    'print_order': 'Ordem de Impressão',
    'profession': 'Profissão',
    'question': 'Questão',
    'rating': 'Avaliação',
    'reason_en': 'Motivo (Inglês)',
    'reason_reprovereq': 'Motivo de Reprovação da Solicitação',
    'register_number': 'Número de Registro',
    'rg': 'RG',
    'salesordernumber': 'Número do Pedido de Vendas',
    'sender': 'Remetente',
    'sender_observations': 'Observações do Remetente',
    'services': 'Serviços',
    'subject_en': 'Assunto (Inglês)',
    'supplier_code': 'Código do Fornecedor',
    'surname': 'Sobrenome',
    'theuser': 'Usuário',
    'title': 'Título',
    'tolerance': 'Tolerância',
    'uf': 'UF',
    'user_password_reset_time': 'Tempo de Redefinição de Senha',
    'xmlfile': 'Arquivo XML',
    'invoice_number': 'Número da Fatura',
    'purchaseordernumber': 'Número do Pedido de Compra',
    'purchaseorderlimit': 'Limite do Pedido de Compra',
    'purchaserequestlimit': 'Limite da Solicitação de Compra',
    'stnumber': 'Número do ST',

    # ── Campos jurídicos ──────────────────────────────────────────────────────
    'lawsuit': 'Processo',
    'plaintiff': 'Autor',
    'defendant': 'Réu',
    'lawyer': 'Advogado',
    'judge': 'Juiz',
    'vara': 'Vara',
    'court': 'Tribunal',
    'city': 'Cidade',
    'state': 'Estado',
    'unit': 'Unidade',
    'businessunit': 'Unidade de Negócio',
    'businessunitgroup': 'Grupo de Unidade de Negócio',
    'businessarea': 'Área de Negócio',
    'paper': 'Papel',
    'link': 'Link',
    'observations': 'Observações',
    'obs': 'Observação',
    'observations_userid': 'Usuário das Observações',
    'correspondent': 'Correspondente',
    'oab': 'OAB',
    'fundamento': 'Fundamento',
    'sentence': 'Sentença',
    'judgement': 'Sentença',
    'perfil': 'Perfil',
    'court_division_name': 'Nome da Divisão do Tribunal',
    'confession': 'Confissão',
    'third_party_presence': 'Presença de Terceiros',
    'deferred_protection': 'Proteção Diferida',
    'alvara': 'Alvará',
    'acomp_location': 'Local de Acompanhamento',
    'agreement_viable_other': 'Outro Acordo Viável',
    'alafile': 'Arquivo ALA',
    'cartorioid': 'ID do Cartório',
    'cartoriosmax': 'Máximo de Cartórios',
    'cnj_required': 'CNJ Obrigatório',
    'competency': 'Competência',
    'court_division_code': 'Código da Divisão do Tribunal',
    'defendant_classification': 'Classificação do Réu',
    'defendant_possible_calcs': 'Cálculos Possíveis do Réu',
    'defendant_probable_calcs': 'Cálculos Prováveis do Réu',
    'defendant_real_calcs': 'Cálculos Reais do Réu',
    'defendant_remote_calcs': 'Cálculos Remotos do Réu',
    'elawsuit': 'E-Processo',
    'esteira': 'Esteira',
    'execucao_provisoria': 'Execução Provisória',
    'final_agreement_proposal': 'Proposta Final de Acordo',
    'homologated_possible_calcs': 'Cálculos Possíveis Homologados',
    'homologated_probable_calcs': 'Cálculos Prováveis Homologados',
    'homologated_remote_calcs': 'Cálculos Remotos Homologados',
    'idcomarca': 'ID da Comarca',
    'idcourt': 'ID do Tribunal',
    'idcourt_division': 'ID da Divisão do Tribunal',
    'impugnation': 'Impugnação',
    'impugnation_result': 'Resultado da Impugnação',
    'individual_lawsuit': 'Processo Individual',
    'instance01_amount': 'Valor da Instância 01',
    'instance02_amount': 'Valor da Instância 02',
    'instanceextra_amount': 'Valor da Instância Extra',
    'instancesup_amount': 'Valor da Instância Superior',
    'jurify_pasta': 'Pasta Jurify',
    'lawsuit_object': 'Objeto do Processo',
    'levantamento': 'Levantamento',
    'loss_diagnosis': 'Diagnóstico de Perda',
    'multipleopna': 'Múltiplas Naturezas de Operação',
    'need_preposto': 'Necessita Preposto',
    'need_witness': 'Necessita Testemunha',
    'new_prazo_update_day': 'Dia de Atualização do Novo Prazo',
    'new_prazo_update_deadline': 'Prazo de Atualização do Novo Prazo',
    'new_protocol_reason': 'Motivo do Novo Protocolo',
    'newjnumberformat': 'Novo Formato de Número Judicial',
    'next_andamento_text': 'Texto do Próximo Andamento',
    'no_lawyer_hearing_email': 'Sem E-mail de Audiência para Advogado',
    'peca_fisica': 'Peça Física',
    'pendencia': 'Pendência',
    'perito_possible_calcs': 'Cálculos Possíveis do Perito',
    'perito_probable_calcs': 'Cálculos Prováveis do Perito',
    'perito_real_calcs': 'Cálculos Reais do Perito',
    'perito_remote_calcs': 'Cálculos Remotos do Perito',
    'plaintiff_possible_calcs': 'Cálculos Possíveis do Autor',
    'plaintiff_probable_calcs': 'Cálculos Prováveis do Autor',
    'plaintiff_real_calcs': 'Cálculos Reais do Autor',
    'plaintiff_remote_calcs': 'Cálculos Remotos do Autor',
    'plaintiffjobrole': 'Cargo do Autor',
    'prazo_goal': 'Meta do Prazo',
    'prazo_hours': 'Horas do Prazo',
    'prazo_type': 'Tipo de Prazo',
    'prazoobs': 'Observação do Prazo',
    'proof_object': 'Objeto de Prova',
    'proposal_amount': 'Valor da Proposta',
    'proposal_observation': 'Observação da Proposta',
    'protocol_confirmed': 'Protocolo Confirmado',
    'protocol_confirmed_date': 'Data de Confirmação do Protocolo',
    'protocol_location': 'Local do Protocolo',
    'protocolrequested': 'Protocolo Solicitado',
    'provamount': 'Valor Provisional',
    'provision': 'Provisão',
    'provisionamount': 'Valor da Provisão',
    'pta': 'PTA',
    'relevantnotes': 'Notas Relevantes',
    'requestprotocol': 'Solicitar Protocolo',
    'result_fundamento': 'Fundamento do Resultado',
    'result_instance': 'Instância do Resultado',
    'result_old': 'Resultado Antigo',
    'sentence_amount_possible': 'Valor de Sentença Possível',
    'sentence_amount_probable': 'Valor de Sentença Provável',
    'sentence_amount_risk': 'Valor de Sentença em Risco',
    'sentenceamount_index_issuer': 'Emissor do Índice do Valor da Sentença',
    'sentenceamount_issuer': 'Emissor do Valor da Sentença',
    'solidarity': 'Solidariedade',
    'solidarity_payment': 'Pagamento Solidário',
    'solidarity_redeemed': 'Solidariedade Resgatada',
    'strategy_level': 'Nível de Estratégia',
    'strategy_motive': 'Motivo de Estratégia',
    'structured_layoff': 'Demissão Estruturada',
    'success_amount': 'Valor de Êxito',
    'totalsentenceamount': 'Valor Total da Sentença',
    'totalsentenceamount_date': 'Data do Valor Total da Sentença',
    'totalsentenceamount_index': 'Índice do Valor Total da Sentença',
    'transito_injulgado': 'Trânsito em Julgado',
    'transito_injulgado_data': 'Data do Trânsito em Julgado',
    'tribunal_manual': 'Tribunal Manual',
    'tribunal_text_manual': 'Texto do Tribunal Manual',
    'turma': 'Turma',
    'turma_2': 'Turma 2',
    'turma_3': 'Turma 3',
    'turma_4': 'Turma 4',
    'vara_number': 'Número da Vara',
    'vara_cartorio_manual': 'Cartório da Vara Manual',

    # ── Campos específicos do SaidJur ─────────────────────────────────────────
    'agreement_viable': 'Acordo Viável',
    'agreement_in_hearing': 'Acordo em Audiência',
    'markup_necessary': 'Markup Necessário',
    'markup_approved': 'Markup Aprovado',
    'markup_reason': 'Motivo do Markup',
    'non_agreement_reason': 'Motivo de Não Acordo',
    'resp_evaluation': 'Responsável da Avaliação',
    'pericia': 'Perícia',
    'pericia_result': 'Resultado da Perícia',
    'prazo': 'Prazo',
    'all_prazos': 'Todos os Prazos',
    'all_clients': 'Todos os Clientes',
    'all_groups': 'Todos os Grupos',
    'date_reference': 'Referência de Data',
    'new_prazo_update_option': 'Opção de Atualização do Novo Prazo',
    'prazo_days': 'Dias do Prazo',
    'type_days': 'Tipo de Dias',
    'user_change_status': 'Usuário que Alterou Status',
    'user_inserted': 'Usuário Inseridor',
    'user_updated': 'Usuário Atualizador',
    'what_lawsuits': 'Quais Processos',
    'publication': 'Publicação',
    'publication_id': 'ID da Publicação',
    'expedient': 'Expediente',
    'expedientfile': 'Arquivo de Expediente',
    'expedientfileobs': 'Observação de Arquivo de Expediente',
    'expedientprotocoldate': 'Data do Protocolo de Expediente',
    'instructions': 'Instruções',
    'instructions_resp': 'Responsável das Instruções',
    'instructions_respfinish': 'Conclusão Responsável Instruções',
    'instructions_sent': 'Instruções Enviadas',
    'instructionsstatus': 'Status das Instruções',
    'instructionstimestamp_userid': 'Usuário do Timestamp Instruções',
    'containsprazo': 'Contém Prazo',
    'noprazoemailsent01': 'E-mail Sem Prazo Enviado',
    'revised': 'Revisado',
    'sent': 'Enviado',
    'naf': 'NAF',
    'naf_userid': 'Usuário NAF',
    'analise_prov': 'Análise Provisória',
    'acomp_encerramento': 'Acompanhamento Encerramento',
    'exprovas': 'Exceção Provas',
    'cumsen': 'Cumprimento Sentença',
    'exccj': 'Exceção CCJ',
    'acum': 'Acumulação',
    'exfis': 'Exceção Fiscal',
    'extiex': 'Exceção TIEX',
    'cartprecciv': 'Cartório Precedência Civil',
    'disconsider': 'Desconsiderar',
    'deleted': 'Excluído',
    'deleted_at_userid': 'Usuário da Exclusão',
    'user_changed_lawsuit': 'Processo Alterado por Usuário',
    'user_changed': 'Alterado por Usuário',
    'includeexpedient': 'Incluir Expediente',
    'cpfl_spreadsheet_import': 'Importação Planilha CPFL',
    'finish_fail': 'Conclusão com Falha',
    'finish_success': 'Conclusão com Êxito',
    'remote': 'Remoto',
    'morto': 'Desativado',
    'no_uf': 'Sem UF',
    'direct_member': 'Membro Direto',
    'insurer_flow': 'Fluxo do Segurador',
    'market_place': 'Mercado',
    'protection_inserted_system': 'Proteção Inserida no Sistema',
    'supplier_flow': 'Fluxo do Fornecedor',
    'transferred': 'Transferido',
    'lawyerdifflevel': 'Nível Diferenciado do Advogado',
    'relativepath': 'Caminho Relativo',
    'topath': 'Caminho de Destino',
    'activate_g_lawsuit': 'Ativar Processo Geral',
    'codigo': 'Código',
    'compdate': 'Data de Compensação',
    'confirm_doc_for_protocol': 'Confirmar Documento para Protocolo',
    'confirm_receive': 'Confirmar Recebimento',
    'confirm_reconcile': 'Confirmar Reconciliação',
    'confirmed_data': 'Dados Confirmados',
    'contains_add': 'Contém Adição',
    'containsfiles': 'Contém Arquivos',
    'containslevfile': 'Contém Arquivo de Levantamento',
    'deadline': 'Prazo',
    'deadlineobs': 'Observação do Prazo',
    'denial_revised': 'Negação Revisada',
    'designated_corresp': 'Correspondente Designado',
    'disconsidered': 'Desconsiderado',
    'driving_demand': 'Demanda Diretora',
    'edit_jud_prazo_dates': 'Editar Datas do Prazo Judicial',
    'edit_jud_prazo_lawyer': 'Editar Advogado do Prazo Judicial',
    'edit_lawsuits_full': 'Editar Processos (Completo)',
    'edit_lawsuits_partial': 'Editar Processos (Parcial)',
    'edit_prazo_dates': 'Editar Datas do Prazo',
    'edit_prazo_lawyer': 'Editar Advogado do Prazo',
    'estimate_picked': 'Estimativa Selecionada',
    'estimatesfinished': 'Estimativas Concluídas',
    'finish_observations': 'Observações de Conclusão',
    'finish_prazo_email_to_supervisor': 'E-mail de Conclusão do Prazo ao Supervisor',
    'finish_prazo_notif': 'Notificação de Conclusão do Prazo',
    'finishdesc': 'Descrição de Conclusão',
    'includedprazo': 'Prazo Incluído',
    'inserted_for_jurify': 'Inserido para Jurify',
    'inserted_userid': 'ID do Usuário Inseridor',
    'markup_observation': 'Observação do Markup',
    'naf_confirmed': 'NAF Confirmado',
    'no_receive_prazo_conf_email_resp': 'Não Receber E-mail de Confirmação de Prazo (Resp.)',
    'no_receive_prazo_confirmation_email': 'Não Receber E-mail de Confirmação de Prazo',
    'nome': 'Nome',
    'pje': 'PJe',
    'prazos_not_finished_business_email': 'E-mail de Prazos Não Concluídos (Comercial)',
    'prazos_not_finished_business_email_resp': 'E-mail de Prazos Não Concluídos Resp. (Comercial)',
    'prazos_not_finished_fatal_email': 'E-mail de Prazos Não Concluídos (Fatal)',
    'prazos_not_finished_fatal_email_resp': 'E-mail de Prazos Não Concluídos Resp. (Fatal)',
    'pubwithoutprazo_email': 'E-mail de Publicação sem Prazo',
    'rateio_busunit': 'Rateio por Unidade de Negócio',
    'rateio_opnaid': 'Rateio por Natureza de Operação',
    'rateio_parentid': 'Rateio por ID Principal',
    'rateio_siblingid': 'Rateio por ID Irmão',
    'receive_prazo_conf_email_resp': 'Receber E-mail de Confirmação de Prazo (Resp.)',
    'receive_prazo_confirmation_email': 'Receber E-mail de Confirmação de Prazo',
    'reconcile': 'Reconciliar',
    'reeimburse': 'Reembolsar',
    'resend_interval': 'Intervalo de Reenvio',
    'resend_on_finish': 'Reenviar ao Concluir',
    'resend_time': 'Horário de Reenvio',
    'return_prazo': 'Devolver Prazo',
    'self_protocol': 'Autoprotocolo',
    'send_expedient': 'Enviar Expediente',
    'send_prazo_email': 'Enviar E-mail de Prazo',
    'send_protocolfile': 'Enviar Arquivo de Protocolo',
    'system_date_proposal_observation': 'Data de Observação da Proposta no Sistema',
    'toggle_code_red': 'Alternar Código Vermelho',
    'toggle_relevant': 'Alternar Relevante',
    'updated_values_calculation': 'Cálculo de Valores Atualizados',
    'user_created_at': 'Data de Criação pelo Usuário',
    'user_updated_at': 'Data de Atualização pelo Usuário',
    'viewresults': 'Ver Resultados',
    'correspcity': 'Cidade do Correspondente',
    'deliverlocation01': 'Local de Entrega 01',
    'deliverlocation02': 'Local de Entrega 02',
    'deliverlocation03': 'Local de Entrega 03',
    'deliverlocationinvoice': 'Local de Entrega (Fatura)',
    'frompath': 'Caminho de Origem',
    'hearingfile': 'Arquivo de Audiência',

    # ── Campos financeiros ─────────────────────────────────────────────────────
    'account': 'Conta',
    'accountspayable': 'Contas a Pagar',
    'accountsreceivable': 'Contas a Receber',
    'acordo_amount': 'Valor do Acordo',
    'acordo_date': 'Data do Acordo',
    'acordo_material_amount': 'Valor Material do Acordo',
    'acordo_moral_amount': 'Valor Moral do Acordo',
    'actualamount': 'Valor Real',
    'actual': 'Real',
    'adm_cost': 'Custo ADM',
    'adm_quantity': 'Quantidade ADM',
    'advance': 'Adiantamento',
    'advanceamount': 'Valor do Adiantamento',
    'advpay': 'Pagamento Antecipado',
    'amountpaid': 'Valor Pago',
    'balance': 'Saldo',
    'bank': 'Banco',
    'billed': 'Faturado',
    'causeamount': 'Valor da Causa',
    'causeamount_index': 'Índice do Valor da Causa',
    'causeamount_index_issuer': 'Emissor do Índice do Valor da Causa',
    'causeamount_issuer': 'Emissor do Valor da Causa',
    'causeamount_possible': 'Valor da Causa Possível',
    'causeamount_probable': 'Valor da Causa Provável',
    'causeamount_remote': 'Valor da Causa Remoto',
    'causeamount_result': 'Resultado do Valor da Causa',
    'causeamount_risk': 'Risco do Valor da Causa',
    'charged_amount': 'Valor Cobrado',
    'com_cost': 'Custo COM',
    'com_quantity': 'Quantidade COM',
    'copies_cost': 'Custo de Cópias',
    'copies_quantity': 'Quantidade de Cópias',
    'corresp_cost': 'Custo do Correspondente',
    'corresp_quantity': 'Quantidade do Correspondente',
    'costamount': 'Valor do Custo',
    'credit_card_number': 'Número do Cartão de Crédito',
    'customrate': 'Taxa Personalizada',
    'customtax': 'Imposto Personalizado',
    'deposit': 'Depósito',
    'destinationaccount': 'Conta de Destino',
    'distcompdatepayments': 'Data de Distribuição dos Pagamentos',
    'dueamount': 'Valor Vencido',
    'effectiveamount': 'Valor Efetivo',
    'emol_cost': 'Custo de Emolumentos',
    'emol_quantity': 'Quantidade de Emolumentos',
    'estimated_amount': 'Valor Estimado',
    'estorno': 'Estorno',
    'expense_report': 'Relatório de Despesas',
    'expensereport': 'Relatório de Despesas',
    'fees_cost': 'Custo de Honorários',
    'fees_quantity': 'Quantidade de Honorários',
    'files_cost': 'Custo de Arquivos',
    'files_quantity': 'Quantidade de Arquivos',
    'finalpayment': 'Pagamento Final',
    'finalpayment_date': 'Data do Pagamento Final',
    'finalpayment_payer': 'Pagador do Pagamento Final',
    'hon_cost': 'Custo de Honorários',
    'hon_quantity': 'Quantidade de Honorários',
    'icms01': 'ICMS 01',
    'icms02': 'ICMS 02',
    'icms03': 'ICMS 03',
    'icmsamount01': 'Valor ICMS 01',
    'icmsamount02': 'Valor ICMS 02',
    'icmsamount03': 'Valor ICMS 03',
    'icmsamountinvoice': 'Valor ICMS (Fatura)',
    'icmsinvoice': 'ICMS (Fatura)',
    'icmsret01': 'ICMS Retido 01',
    'icmsret02': 'ICMS Retido 02',
    'icmsret03': 'ICMS Retido 03',
    'icmsretinvoice': 'ICMS Retido (Fatura)',
    'income': 'Receita',
    'index_value': 'Valor do Índice',
    'installment': 'Parcela',
    'installments': 'Parcelas',
    'intern_cost': 'Custo Interno',
    'intern_quantity': 'Quantidade Interna',
    'invoice': 'Fatura',
    'ir': 'IR',
    'irrf01': 'IRRF 01',
    'irrf02': 'IRRF 02',
    'irrf03': 'IRRF 03',
    'irrfamount01': 'Valor IRRF 01',
    'irrfamount02': 'Valor IRRF 02',
    'irrfamount03': 'Valor IRRF 03',
    'irrfamountinvoice': 'Valor IRRF (Fatura)',
    'irrfinvoice': 'IRRF (Fatura)',
    'irrfret01': 'IRRF Retido 01',
    'irrfret02': 'IRRF Retido 02',
    'irrfret03': 'IRRF Retido 03',
    'irrfretinvoice': 'IRRF Retido (Fatura)',
    'issn01': 'ISS 01',
    'issn02': 'ISS 02',
    'issn03': 'ISS 03',
    'issnamount01': 'Valor ISS 01',
    'issnamount02': 'Valor ISS 02',
    'issnamount03': 'Valor ISS 03',
    'issnamountinvoice': 'Valor ISS (Fatura)',
    'issninvoice': 'ISS (Fatura)',
    'issnret01': 'ISS Retido 01',
    'issnret02': 'ISS Retido 02',
    'issnret03': 'ISS Retido 03',
    'issnretinvoice': 'ISS Retido (Fatura)',
    'issuer': 'Emissor',
    'issuer_defendant': 'Emissor do Réu',
    'last_salary': 'Último Salário',
    'legal_fees': 'Honorários Advocatícios',
    'lodging_cost': 'Custo de Hospedagem',
    'lodging_quantity': 'Quantidade de Hospedagem',
    'mastercard': 'Mastercard',
    'meals_cost': 'Custo de Refeições',
    'meals_quantity': 'Quantidade de Refeições',
    'netamount': 'Valor Líquido',
    'newbalance': 'Novo Saldo',
    'otherincome_cost': 'Custo de Outros Rendimentos',
    'otherincome_quantity': 'Quantidade de Outros Rendimentos',
    'othertrips_cost': 'Custo de Outras Viagens',
    'othertrips_quantity': 'Quantidade de Outras Viagens',
    'overhead_cost': 'Custo de Overhead',
    'overhead_quantity': 'Quantidade de Overhead',
    'overvariation': 'Variação Superior',
    'paid_by': 'Pago por',
    'payment': 'Pagamento',
    'paymentform01': 'Forma de Pagamento 01',
    'paymentform02': 'Forma de Pagamento 02',
    'paymentform03': 'Forma de Pagamento 03',
    'paymentforminvoice': 'Forma de Pagamento (Fatura)',
    'pis01': 'PIS 01',
    'pis02': 'PIS 02',
    'pis03': 'PIS 03',
    'pisamount01': 'Valor PIS 01',
    'pisamount02': 'Valor PIS 02',
    'pisamount03': 'Valor PIS 03',
    'pisamountinvoice': 'Valor PIS (Fatura)',
    'pisinvoice': 'PIS (Fatura)',
    'pisret01': 'PIS Retido 01',
    'pisret02': 'PIS Retido 02',
    'pisret03': 'PIS Retido 03',
    'pisretinvoice': 'PIS Retido (Fatura)',
    'product_amount': 'Valor do Produto',
    'productiverate': 'Taxa de Produtividade',
    'reemb_cost': 'Custo de Reembolso',
    'reemb_quantity': 'Quantidade de Reembolso',
    'reimb': 'Reembolso',
    'revenue': 'Receita',
    'risk_amount': 'Valor do Risco',
    'risk_estimate': 'Estimativa de Risco',
    'salaryandbenefits': 'Salário e Benefícios',
    'salesman_01': 'Vendedor 01',
    'salesman_02': 'Vendedor 02',
    'salesman_03': 'Vendedor 03',
    'sent_payables': 'Pagáveis Enviados',
    'service_provider': 'Prestador de Serviço',
    'service_provider_payment': 'Pagamento ao Prestador de Serviço',
    'settlement': 'Liquidação',
    'shipping': 'Envio',
    'splitpayments': 'Divisão de Pagamentos',
    'splitreceivable': 'Divisão de Recebíveis',
    'subsidy': 'Subsídio',
    'subsidy_available': 'Subsídio Disponível',
    'subsidy_quality': 'Qualidade do Subsídio',
    'success_id': 'ID de Êxito',
    'taxi_cost': 'Custo de Táxi',
    'taxi_quantity': 'Quantidade de Táxi',
    'totalamount': 'Valor Total',
    'totalamount01': 'Valor Total 01',
    'totalamount02': 'Valor Total 02',
    'totalamount03': 'Valor Total 03',
    'totalamountinvoice': 'Valor Total (Fatura)',
    'totalprice01': 'Preço Total 01',
    'totalprice02': 'Preço Total 02',
    'totalprice03': 'Preço Total 03',
    'totalpriceinvoice': 'Preço Total (Fatura)',
    'totalprovamount': 'Valor Provisional Total',
    'totalprovamount_index': 'Índice do Valor Provisional Total',
    'totalprovamount_index_issuer': 'Emissor do Índice do Valor Provisional Total',
    'totalprovamount_issuer': 'Emissor do Valor Provisional Total',
    'totalprovamount_possible': 'Valor Provisional Total Possível',
    'totalprovamount_probable': 'Valor Provisional Total Provável',
    'totalprovamount_remote': 'Valor Provisional Total Remoto',
    'transfer': 'Transferência',
    'trips_cost': 'Custo de Viagens',
    'trips_quantity': 'Quantidade de Viagens',
    'undervariation': 'Variação Inferior',
    'unitprice01': 'Preço Unitário 01',
    'unitprice02': 'Preço Unitário 02',
    'unitprice03': 'Preço Unitário 03',
    'unitpriceinvoice': 'Preço Unitário (Fatura)',
    'unproductiverate': 'Taxa de Improdutividade',
    'withdrawl': 'Saque',
    'workrate': 'Taxa de Trabalho',

    # ── Booleanos ─────────────────────────────────────────────────────────────
    'active': 'Ativo',
    'archived': 'Arquivado',
    'visible': 'Visível',
    'enabled': 'Habilitado',
    'canceled': 'Cancelado',
    'rescheduled': 'Reagendado',
    'sinedie': 'Sem Hora Marcada',
    'confirmed': 'Confirmado',
    'deactivated': 'Desativado',
    'approved': 'Aprovado',
    'automatic': 'Automático',
    'denied': 'Negado',
    'denied_by': 'Negado por',
    'delivered': 'Entregue',
    'dispensed': 'Dispensado',
    'finished': 'Concluído',
    'fixed': 'Fixo',
    'internal': 'Interno',
    'migrated': 'Migrado',
    'online': 'Online',
    'operational': 'Operacional',
    'pause': 'Pausa',
    'relevant': 'Relevante',
    'required_todo': 'Tarefa Obrigatória',
    'resent': 'Reenviado',
    'returned': 'Devolvido',
    'skip_validate': 'Pular Validação',
    'start': 'Início',
    'stop': 'Parar',
    'validate': 'Validar',
    'viewed': 'Visualizado',
    'client_sys_updated': 'Sistema do Cliente Atualizado',
    'close_gerencial': 'Encerrado Gerencialmente',
    'closed_gerencial': 'Encerrado Gerencialmente',
    'code_red': 'Código Vermelho',
    'finished_invoice': 'Fatura Concluída',
    'lawyerfinished': 'Advogado Concluído',
    'hearingresp_confirmed': 'Responsável da Audiência Confirmado',
    'time_confirmed': 'Horário Confirmado',
    'timeconfirmed': 'Horário Confirmado',
    'entrytype_p_approved': 'Lançamento de Tipo P Aprovado',

    # ── Comunicação ───────────────────────────────────────────────────────────
    'email': 'E-mail',
    'phone': 'Telefone',
    'message': 'Mensagem',
    'subject': 'Assunto',
    'content': 'Conteúdo',
    'text': 'Texto',
    'recipienttype': 'Tipo de Destinatário',
    'receiver': 'Destinatário',
    'serveremail': 'Servidor de E-mail',
    'serveremailpwd': 'Senha do Servidor de E-mail',
    'coordinator_hearing_email': 'E-mail de Audiência do Coordenador',
    'busdead_email': 'E-mail de Prazo Comercial',
    'fataldead_email': 'E-mail de Prazo Fatal',
    'compdeadlineemail01': 'E-mail de Prazo da Empresa 01',
    'compdeadlineemail02': 'E-mail de Prazo da Empresa 02',
    'fataldeadlineemail01': 'E-mail de Prazo Fatal 01',
    'fataldeadlineemail02': 'E-mail de Prazo Fatal 02',
    'client_receiver': 'Destinatário do Cliente',
    'client_reference': 'Referência do Cliente',
    'client_system': 'Sistema do Cliente',
    'client_system_limit': 'Limite do Sistema do Cliente',
    'client_lawyer': 'Advogado do Cliente',
    'client_access': 'Acesso do Cliente',

    # ── Arquivos ──────────────────────────────────────────────────────────────
    'file': 'Arquivo',
    'filepath': 'Caminho do Arquivo',
    'filesize': 'Tamanho do Arquivo',

    # ── Controle e auditoria ──────────────────────────────────────────────────
    'created_by': 'Criado por',
    'updated_by': 'Atualizado por',
    'deleted_by': 'Excluído por',
    'inserted_by': 'Inserido por',
    'accesscondition': 'Condição de Acesso',
    'cron': 'Agendamento',
    'current_location': 'Localização Atual',
    'user_del': 'Usuário Excluidor',
    'user_disconsidered': 'Usuário Desconsiderador',
    'userchangedid': 'ID do Usuário que Alterou',
    'instructionsinsert_userid': 'Usuário de Inserção das Instruções',
    'instructionsupdate_userid': 'Usuário de Atualização das Instruções',
    'log_inserted_at': 'Data de Inserção do Log',
    'source_api': 'API de Origem',
    'admprazo': 'Prazo ADM',

    # ── Permissões ─────────────────────────────────────────────────────────────
    'access_client_all': 'Acesso a Todos os Clientes',
    'approve_contracts': 'Aprovar Contratos',
    'approve_expensereport': 'Aprovar Relatório de Despesas',
    'approve_invoice': 'Aprovar Fatura',
    'approve_lawsuitbudget': 'Aprovar Orçamento do Processo',
    'approve_order': 'Aprovar Pedido',
    'approve_purchaseinvoice': 'Aprovar Fatura de Compra',
    'approve_purchaseorder': 'Aprovar Pedido de Compra',
    'approve_purchaserequest': 'Aprovar Solicitação de Compra',
    'approve_request': 'Aprovar Solicitação',
    'approvesales': 'Aprovar Vendas',
    'cancel_hearings': 'Cancelar Audiências',
    'cancel_prazo': 'Cancelar Prazo',
    'change_pub_lawsuit': 'Alterar Processo da Publicação',
    'change_users_pwd': 'Alterar Senha dos Usuários',
    'close_f_lawsuit': 'Encerrar Processo Fatal',
    'close_g_lawsuit': 'Encerrar Processo Geral',
    'close_lawsuit': 'Encerrar Processo',
    'close_prazos': 'Encerrar Prazos',
    'delete_log': 'Excluir Log',
    'delete_prazo': 'Excluir Prazo',
    'del_andamentos': 'Excluir Andamentos',
    'del_lawsuit': 'Excluir Processo',
    'del_lawsuitdocs': 'Excluir Documentos do Processo',
    'del_otherdocs': 'Excluir Outros Documentos',
    'del_pub_with_prazos': 'Excluir Publicação com Prazos',
    'follow_generaltasks': 'Acompanhar Tarefas Gerais',
    'follow_lawsuittasks': 'Acompanhar Tarefas do Processo',
    'full_bu_access': 'Acesso Total à Unidade de Negócio',
    'insert_clients': 'Inserir Clientes',
    'insert_date_field': 'Inserir Campo de Data',
    'insert_docs': 'Inserir Documentos',
    'read_accountpayreport': 'Ver Relatório de Contas a Pagar',
    'read_accountrecreport': 'Ver Relatório de Contas a Receber',
    'read_accounts': 'Ver Contas',
    'read_accountspay': 'Ver Contas a Pagar',
    'read_accountsrec': 'Ver Contas a Receber',
    'read_all_accountspay': 'Ver Todas as Contas a Pagar',
    'read_all_prazoreport': 'Ver Todos os Relatórios de Prazo',
    'read_allhearings': 'Ver Todas as Audiências',
    'read_appropreport': 'Ver Relatório de Aprovação',
    'read_audit': 'Ver Auditoria',
    'read_bankrecon': 'Ver Reconciliação Bancária',
    'read_busunit': 'Ver Unidade de Negócio',
    'read_cashflowreport': 'Ver Relatório de Fluxo de Caixa',
    'read_clientdoc': 'Ver Documento do Cliente',
    'read_clients': 'Ver Clientes',
    'read_com': 'Ver Comunicação',
    'read_con': 'Ver Contratos',
    'read_configbusiness': 'Ver Configuração do Negócio',
    'read_configconsultaudit': 'Ver Configuração de Consulta/Auditoria',
    'read_configexpensereports': 'Ver Configuração de Relatórios de Despesas',
    'read_configjurisp': 'Ver Configuração de Jurisprudência',
    'read_configlawsuits': 'Ver Configuração de Processos',
    'read_configprazos': 'Ver Configuração de Prazos',
    'read_configpublications': 'Ver Configuração de Publicações',
    'read_configtasks': 'Ver Configuração de Tarefas',
    'read_configtemplate': 'Ver Configuração de Templates',
    'read_consult': 'Ver Consultas',
    'read_contracts': 'Ver Contratos',
    'read_controllerlawsuits': 'Ver Controle de Processos',
    'read_controlpanel': 'Ver Painel de Controle',
    'read_employees': 'Ver Funcionários',
    'read_expedient': 'Ver Expediente',
    'read_expensereport': 'Ver Relatório de Despesas',
    'read_financialdashboard': 'Ver Dashboard Financeiro',
    'read_generaltasks': 'Ver Tarefas Gerais',
    'read_hearings': 'Ver Audiências',
    'read_inventory': 'Ver Inventário',
    'read_jobroles': 'Ver Cargos',
    'read_jurisp': 'Ver Jurisprudência',
    'read_lawhourrate': 'Ver Taxa Horária do Advogado',
    'read_lawsuitbudget': 'Ver Orçamento de Processo',
    'read_lawsuits': 'Ver Processos',
    'read_lawsuittasks': 'Ver Tarefas do Processo',
    'read_opnature': 'Ver Natureza de Operação',
    'read_payments': 'Ver Pagamentos',
    'read_paytype': 'Ver Tipo de Pagamento',
    'read_protocoldoc': 'Ver Documento de Protocolo',
    'read_publications': 'Ver Publicações',
    'read_pubprodreport': 'Ver Relatório de Produtividade de Publicações',
    'read_purchaseestimates': 'Ver Estimativas de Compra',
    'read_purchaseinvoice': 'Ver Fatura de Compra',
    'read_purchaseorder': 'Ver Pedido de Compra',
    'read_purchaserequest': 'Ver Solicitação de Compra',
    'read_resultreport': 'Ver Relatório de Resultados',
    'read_strategiclawsuits': 'Ver Processos Estratégicos',
    'read_strategiclawsuits2': 'Ver Processos Estratégicos 2',
    'read_suppliers': 'Ver Fornecedores',
    'read_taskcontrolreport': 'Ver Relatório de Controle de Tarefas',
    'read_tax': 'Ver Impostos',
    'read_template': 'Ver Template',
    'read_timesheet': 'Ver Timesheet',
    'read_transfers': 'Ver Transferências',
    'read_users': 'Ver Usuários',
    'reprove_request': 'Reprovar Solicitação',
    'set_adm': 'Definir ADM',
    'set_ph01': 'Definir PH01',
    'set_ph02': 'Definir PH02',
    'set_ph03': 'Definir PH03',
    'write_accountpayreport': 'Editar Relatório de Contas a Pagar',
    'write_accounts': 'Editar Contas',
    'write_accountspay': 'Editar Contas a Pagar',
    'write_accountsrec': 'Editar Contas a Receber',
    'write_audit': 'Editar Auditoria',
    'write_busunit': 'Editar Unidade de Negócio',
    'write_claims': 'Editar Pedidos',
    'write_clientdoc': 'Editar Documento do Cliente',
    'write_clients': 'Editar Clientes',
    'write_com': 'Editar Comunicação',
    'write_con': 'Editar Contratos',
    'write_configbusiness': 'Editar Configuração do Negócio',
    'write_configconsultaudit': 'Editar Configuração de Consulta/Auditoria',
    'write_configexpensereports': 'Editar Configuração de Relatórios de Despesas',
    'write_configjurisp': 'Editar Configuração de Jurisprudência',
    'write_configlawsuits': 'Editar Configuração de Processos',
    'write_configprazos': 'Editar Configuração de Prazos',
    'write_configpublications': 'Editar Configuração de Publicações',
    'write_configtasks': 'Editar Configuração de Tarefas',
    'write_configtemplate': 'Editar Configuração de Templates',
    'write_consult': 'Editar Consultas',
    'write_contracts': 'Editar Contratos',
    'write_controlpanel': 'Editar Painel de Controle',
    'write_employees': 'Editar Funcionários',
    'write_expedient': 'Editar Expediente',
    'write_generaltasks': 'Editar Tarefas Gerais',
    'write_hearings': 'Editar Audiências',
    'write_inventory': 'Editar Inventário',
    'write_jobroles': 'Editar Cargos',
    'write_jurisp': 'Editar Jurisprudência',
    'write_lawhourrate': 'Editar Taxa Horária do Advogado',
    'write_lawsuits': 'Editar Processos',
    'write_lawsuittasks': 'Editar Tarefas do Processo',
    'write_no_cnj': 'Editar Processos sem CNJ',
    'write_opnature': 'Editar Natureza de Operação',
    'write_payments': 'Editar Pagamentos',
    'write_paytype': 'Editar Tipo de Pagamento',
    'write_persons': 'Editar Pessoas',
    'write_prazo_closed_lawsuits': 'Editar Prazo em Processos Encerrados',
    'write_prazoreport': 'Editar Relatório de Prazos',
    'write_protocoldoc': 'Editar Documento de Protocolo',
    'write_pub_weekend': 'Editar Publicações no Fim de Semana',
    'write_publications': 'Editar Publicações',
    'write_purchaseestimates': 'Editar Estimativas de Compra',
    'write_purchaseinvoice': 'Editar Fatura de Compra',
    'write_purchaseorder': 'Editar Pedido de Compra',
    'write_purchaserequest': 'Editar Solicitação de Compra',
    'write_suppliers': 'Editar Fornecedores',
    'write_tax': 'Editar Impostos',
    'write_template': 'Editar Template',
    'write_timesheet': 'Editar Timesheet',
    'write_transfers': 'Editar Transferências',
    'write_users': 'Editar Usuários',

    # ── Permissões de correspondente ──────────────────────────────────────────
    'access_module': 'Módulo de Acesso',
    'approve_requests': 'Aprovar Solicitações',
    'close_requests': 'Fechar Solicitações',
    'designate_correspondent': 'Designar Correspondente',
    'edit_requests_all': 'Editar Todas as Solicitações',
    'view_finance': 'Ver Financeiro',
    'view_log': 'Ver Log',
    'view_requests': 'Ver Solicitações',
    'view_requests_all': 'Ver Todas as Solicitações',
    'write_requests': 'Escrever Solicitações',

    # ── Pessoas e Papéis ──────────────────────────────────────────────────────
    'agent': 'Agente',
    'buyer_resp': 'Responsável da Compra',
    'check_date_resp': 'Responsável da Data de Conferência',
    'hearing_resp': 'Responsável da Audiência',
    'internal_resp': 'Responsável Interno',
    'instructions_sender': 'Remetente das Instruções',
    'legal_assistant': 'Assistente Jurídico',
    'lawsuit_resp': 'Responsável do Processo',
    'preposto_1': 'Preposto 1',
    'preposto_2': 'Preposto 2',
    'preposto_disfav_result_motive': 'Motivo do Resultado Desfavorável do Preposto',
    'preposto_fav_result_motive': 'Motivo do Resultado Favorável do Preposto',
    'preposto_favorable_result': 'Resultado Favorável do Preposto',
    'preposto_name': 'Nome do Preposto',
    'preposto_obs': 'Observação do Preposto',
    'preposto_performance': 'Desempenho do Preposto',
    'preposto_phone': 'Telefone do Preposto',
    'representative': 'Representante',
    'role_bank': 'Papel do Banco',
    'role_client': 'Papel do Cliente',
    'role_clientlawyer': 'Papel do Advogado do Cliente',
    'role_correspondente': 'Papel do Correspondente',
    'role_defendant': 'Papel do Réu',
    'role_desembargador': 'Papel do Desembargador',
    'role_employee': 'Papel do Funcionário',
    'role_judge': 'Papel do Juiz',
    'role_otherlawyer': 'Papel do Outro Advogado',
    'role_plaintiff': 'Papel do Autor',
    'role_supplier': 'Papel do Fornecedor',
    'role_tech_assistant': 'Papel do Assistente Técnico',
    'role_witness': 'Papel da Testemunha',
    'seller_resp': 'Responsável de Vendas',
    'witness_1': 'Testemunha 1',
    'witness_2': 'Testemunha 2',
    'witness_1_disfav_result_motive': 'Motivo do Resultado Desfavorável da Testemunha 1',
    'witness_1_fav_result_motive': 'Motivo do Resultado Favorável da Testemunha 1',
    'witness_1_favorable_result': 'Resultado Favorável da Testemunha 1',
    'witness_1_name': 'Nome da Testemunha 1',
    'witness_1_obs': 'Observação da Testemunha 1',
    'witness_1_phone': 'Telefone da Testemunha 1',
    'witness_2_disfav_result_motive': 'Motivo do Resultado Desfavorável da Testemunha 2',
    'witness_2_fav_result_motive': 'Motivo do Resultado Favorável da Testemunha 2',
    'witness_2_favorable_result': 'Resultado Favorável da Testemunha 2',
    'witness_2_name': 'Nome da Testemunha 2',
    'witness_2_obs': 'Observação da Testemunha 2',
    'witness_2_phone': 'Telefone da Testemunha 2',
    'witness_performance': 'Desempenho da Testemunha',

    # ── Adicionais ────────────────────────────────────────────────────────────
    'url': 'URL',
    'path': 'Caminho',
    'reference': 'Referência',
    'comments': 'Comentários',
    'notes': 'Notas',
    'details': 'Detalhes',
    'reason': 'Motivo',

    # ── Complementos identificados no relatório de auditoria ──────────────────
    # Entidades base (permitem tradução automática de <entidade>_id)
    'activity': 'Atividade',
    'business': 'Negócio',
    'task': 'Tarefa',
    # Campos gerais
    'level': 'Nível',
    'parent_id': 'ID Principal',
    'transition': 'Transição',
    'other': 'Outro',
    'others': 'Outros',
    'quantity': 'Quantidade',
    'responsibility': 'Responsabilidade',
    'resume': 'Resumo',
    'justification': 'Justificativa',
    # Datas e horários
    'hearingdate': 'Data da Audiência',
    'hearingtime': 'Horário da Audiência',
    'hearingtype': 'Tipo de Audiência',
    'open_g_date': 'Data de Abertura Geral',
    'close_g_date': 'Data de Encerramento Geral',
    'close_prov_date': 'Data de Encerramento Provisório',
    'status_changed_at': 'Data de Alteração de Status',
    'status_changed_userid': 'Usuário da Alteração de Status',
    'external_date': 'Data Externa',
    'ref_date': 'Data de Referência',
    'timesent': 'Horário de Envio',
    'timechanged': 'Horário da Alteração',
    'occurancedate': 'Data de Ocorrência',
    'udpated_at': 'Data de Atualização',
    'data_atualizacao': 'Data de Atualização',
    'starttime': 'Hora de Início',
    'endtime': 'Hora de Término',
    'isalldayevent': 'Evento de Dia Inteiro',
    'color': 'Cor',
    'recurringrule': 'Regra de Recorrência',
    'date01': 'Data 01',
    'date02': 'Data 02',
    'data_2': 'Data 2',
    'data_3': 'Data 3',
    'data_4': 'Data 4',
    # IDs complementares
    'automaticprazo_id': 'ID do Prazo Automático',
    'closed_userid': 'Usuário do Encerramento',
    'close_userid': 'Usuário do Encerramento',
    'closed_by': 'Encerrado por',
    'id_jurify': 'ID Jurify',
    'opnatureprop_id': 'ID da Proposta de Natureza de Operação',
    'task2pub_id': 'ID da Publicação da Tarefa',
    'parent_lawsuit_id': 'ID do Processo Principal',
    # Valores financeiros numerados
    'amount01': 'Valor 01',
    'amount02': 'Valor 02',
    'quant_estimate01': 'Estimativa de Quantidade 01',
    'quant_estimate02': 'Estimativa de Quantidade 02',
    'quant_estimate03': 'Estimativa de Quantidade 03',
    'quantityinvoice': 'Quantidade (Fatura)',
    'print_estimate01': 'Estimativa de Impressão 01',
    'print_estimate02': 'Estimativa de Impressão 02',
    'print_estimate03': 'Estimativa de Impressão 03',
    'file_estimate01': 'Estimativa de Arquivo 01',
    'file_estimate02': 'Estimativa de Arquivo 02',
    'file_estimate03': 'Estimativa de Arquivo 03',
    'supplier01': 'Fornecedor 01',
    'supplier02': 'Fornecedor 02',
    'supplier03': 'Fornecedor 03',
    # Campos jurídicos complementares
    'procuracao': 'Procuração',
    'procuracao_status': 'Status da Procuração',
    'difflevel': 'Nível Diferenciado',
    'lawsuitdifflevel': 'Nível Diferenciado do Processo',
    'containstypefile': 'Contém Tipo de Arquivo',
    'close_result': 'Resultado do Encerramento',
    'termination_reason': 'Motivo de Rescisão',
    'total_payment_guarantee': 'Total de Garantia de Pagamento',
    'from_expensereport': 'Originário de Relatório de Despesas',
    'from_acordo_nucleus': 'Do Núcleo de Acordo',
    # Campos financeiros complementares
    'sourceaccount': 'Conta de Origem',
    # Campos organizacionais
    'all_states': 'Todos os Estados',
    'cost_center_1': 'Centro de Custo 1',
    'cost_center_2': 'Centro de Custo 2',
    'cost_center_name': 'Nome do Centro de Custo',
    'supervisor_prazo_email': 'E-mail de Prazo do Supervisor',
}


_SUBSTANTIVOS_MASCULINOS_EM_A = {
    'mapa',
    'prazo',
    'problema',
    'programa',
    'sistema',
    'tema',
}


def _normalizar_palavra(texto: str) -> str:
    return ''.join(
        char
        for char in unicodedata.normalize('NFD', texto.lower())
        if unicodedata.category(char) != 'Mn'
    )


def _artigo_para_id(traducao_base: str) -> str:
    primeira_palavra = traducao_base.split()[0]
    palavra_normalizada = _normalizar_palavra(primeira_palavra)

    if palavra_normalizada.endswith(('agem', 'cao', 'dade', 'gem', 'ice', 'sao')):
        return 'da'

    if (
        palavra_normalizada.endswith('a')
        and palavra_normalizada not in _SUBSTANTIVOS_MASCULINOS_EM_A
    ):
        return 'da'

    return 'do'


def _traduzir_coluna_relacional(nome_coluna: str) -> str | None:
    if not nome_coluna.endswith('_id'):
        return None

    entidade = nome_coluna[:-3]
    traducao_entidade = TRADUCOES_COLUNAS.get(entidade)
    if not traducao_entidade:
        return None

    return f"ID {_artigo_para_id(traducao_entidade)} {traducao_entidade}"


def traduzir_nome_coluna(nome_coluna):
    """Traduz nome da coluna para português."""
    if not nome_coluna:
        return nome_coluna

    nome_coluna = nome_coluna.lower()

    # Tradução direta
    if nome_coluna in TRADUCOES_COLUNAS:
        return TRADUCOES_COLUNAS[nome_coluna]

    traducao_relacional = _traduzir_coluna_relacional(nome_coluna)
    if traducao_relacional:
        return traducao_relacional

    # Tentar traduzir partes
    partes = nome_coluna.split('_')
    partes_traduzidas = []

    for parte in partes:
        if parte in TRADUCOES_COLUNAS:
            partes_traduzidas.append(TRADUCOES_COLUNAS[parte])
        elif parte == 'id':
            partes_traduzidas.append('ID')
        else:
            partes_traduzidas.append(parte.capitalize())

    return ' '.join(partes_traduzidas)